### ISSUE TITLE
termux-url-open broken in android 10

### ISSUE THREAD

**Issue by benaiu** [termux/TermuxAm#3]
after update to android 10, termux-url-open doesn't open urls if termux is in background.
I was looking for verbose, doesn't have
checked exit code always 0 , if it works or not
so went to the script tried to run the standalone command:
```
$ am start --user current -a android.intent.action.VIEW -d "https://termux.com/issues" ; echo $?
Starting: Intent { act=android.intent.action.VIEW dat=https://termux.com/... }
0
```
system doesn't bat an eye

**Comment by ghost** [comment]
That's a behavior of Android 10 regarding foreground vs background apps...
