### ISSUE TITLE
How to launch Activity intent from the background?

### ISSUE THREAD

**Issue by lytex** [termux/TermuxAm#4]
First of all thank you for Termux! It is speeding up a lot Android development for people like me who has no idea of the platform, allowing us to hack together some bash scripts :)

With the introduction of Android 10, there are many [restrictions](https://stackoverflow.com/questions/60767216/how-to-trigger-a-launch-activity-intent-when-my-app-is-closed-on-android-10-q) to launch an activity where the app is not on the foreground, but I want to launch activities from a termux task running in the background.

Currently, as a workaround, I'm keeping termux always open using Termux:Float so that intents always work.
Is there a way to do it better?

**Comment by ghost** [comment]
> Is there a way to do it better?

A better way will be use of `am` from the root shell. Requires a rooted device, of course.

That restriction can't be bypassed in normal way, otherwise it would be just pointless. Its purpose is
> keep the user more in control of what's shown on their screen

**Comment by lytex** [comment]
It seems there's a less drastic way to make it work without root:

https://www.reddit.com/r/tasker/comments/dl47bt/tasker_android_10_starting_activities_without/

By giving Termux permission to Draw over other apps, it can lanuch activities in the background, at least in my phone

Another options could be:

- Notification Access
- Accessibility Access
- Device Admin

but termux doesn't ask this permissions so I think there is no way to give them to it
